name: codigo-limpio-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scikit-learn
  - pandas
  - numpy
  - pytest
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - yaml
  - seaborn = 0.11.2
  - plotly
  - pylint
  - autopep8
