main:
  components_repository: "https://github.com/David-Damian/buenas_practicas_codigo"
  project_name: tranformando_codigo_sucio_a_código_limpio
  steps: all

data:
  TRAIN_PATH: "./data/raw/train.csv"
  TEST_PATH: "./data/raw/test.csv"
  TRAIN_CLEAN: "./data/clean/"
  TEST_CLEAN: "./data/clean/"  
  TRAIN_PROCESSED: "./data/processed/"
  TEST_PROCESSED: "./data/processed/"
  PREDICCIONES: "./data/predicciones/"

visualization:
  FIGURES_PATH: "./figures/"

