main:
  components_repository: "https://github.com/David-Damian/buenas_practicas_codigo"
  project_name: tranformando_codigo_sucio_a_código_limpio
  steps: all

data:
  train_data: "data/raw/train.csv"
  test_data: "data/raw/test.csv"